language: rust
sudo: required
services:
  - docker
env:
  global:
    - image: dabbot/sharder

branches:
  only:
  - master
  - /^v.*$/

before_install:
  - pip install -U pip

before_script:
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image" .

before_deploy:
  - docker --version
  - pip install --user --upgrade awscli
  - export PATH=$PATH:/$HOME/.local/bin
  - eval $(aws ecr get-login --region ${REGION})

  deploy:
    provider: script
    script: docker tag "$image" "${image}:latest" && docker tag "$image" "${image}:${TRAVIS_TAG}" && docker push ${ECR_URL}/${image}:${TRAVIS_TAG}
    on:
      tags: true