language: rust
rust:
  - nightly-2018-12-26
sudo: required
services:
  - docker
env:
  global:
    - IMAGE=dabbot/sharder

branches:
  only:
    - master
    - /^v.*$/

before_script:
  - docker pull "$IMAGE" || true

script:
  - docker build --pull --cache-from "$IMAGE" -t "$IMAGE" .

before_deploy:
  - docker --version
  - pip install --user --upgrade awscli
  - pip install --user urllib3[secure]
  - export PATH=$PATH:/$HOME/.local/bin
  - eval $(aws ecr get-login --region ${REGION} --no-include-email)

deploy:
  provider: script
  script: docker tag "$IMAGE" "${IMAGE}:latest" && docker tag "$IMAGE" "${IMAGE}:${TRAVIS_TAG}" && docker push ${ECR_URL}/${IMAGE}:${TRAVIS_TAG}
  on:
    tags: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
