language: rust
sudo: required
services:
  - docker
env:
  global:
    - IMAGE=dabbot/sharder

branches:
  only:
    - master
    - /^v.*$/

before_install:
  - pip install --upgrade pip

before_script:
  - docker pull "$IMAGE" || true

script:
  - docker build --pull --cache-from "$IMAGE" -t "$IMAGE" .

before_deploy:
  - docker --version
  - pip install --user --upgrade awscli
  - export PATH=$PATH:/$HOME/.local/bin
  - eval $(aws ecr get-login --region ${REGION})

deploy:
  provider: script
  script: docker tag "$IMAGE" "${IMAGE}:latest" && docker tag "$IMAGE" "${IMAGE}:${TRAVIS_TAG}" && docker push ${ECR_URL}/${IMAGE}:${TRAVIS_TAG}
  on:
    tags: true