version: '2'

services:
  redis:
    image: redis:alpine
    container_name: sharder_redis
    expose:
      - 6379

  app:
    build: .
    container_name: sharder
    depends_on:
      - redis
    links:
      - redis
    environment:
      DISCORD_SHARD_START: ${DISCORD_SHARD_START}
      DISCORD_SHARD_TOTAL: ${DISCORD_SHARD_TOTAL}
      DISCORD_SHARD_UNTIL: ${DISCORD_SHARD_UNTIL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      REDIS_ADDR: ${REDIS_ADDR}
      RUST_LOG: ${RUST_LOG}
